### ISSUE TITLE
Guide for handling SPAs with client-side routers

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/workers-docs#439]
For the most part, using Workers Sites makes sense for most static asset servers. As soon as you introduce an SPA that handles its own routing, with a tool like React Router for example, things get a little trickier. This isn't unique to Workers Sites; similar configuration is necessary when serving from other web server technologies, but we should provide a guide to handling these scenarios, if not a snippet or package function.

An example that led me to looking at this: I've been using [mdx-deck](https://github.com/jxnblk/mdx-deck) for a presentation, and I wanted to deploy it using sites. Initial load of the site is fine, but if I'm in the middle of the deck and reload, the browser asks for `deck.a.workers.dev/7`, for example, which leads the worker to look for the asset at `7/index.html`, which does not work. What this Worker should do is see that the path matches a specific pattern (in this case, has no mime type because there is an SPA at this route), and instead fall back to serving the asset at the root, `index.html`, which will then serve the app.

I believe this falls under the category of custom asset handler logic; we could either publish a generalized version of this logic as part of the kv-asset-handler package, or include it as part of the template gallery. At minimum, though, I think it is worth calling out in our documentation as a weird case, with an example of how to handle it.

**Comment by victoriabernard92** [comment]
> deck.a.workers.dev/7, for example, which leads the worker to look for the asset at 7/index.html, which does not work. 

Why would that not work? There should be a page at `7/index.html` is they want to serve HTML at `/7` 

I think this is a really specific issue we could maybe document in the handler readme

**Comment by signalnerve** [comment]
Good call! @ashleymichal we should be able to set up a key handler to just always look up index.html, and then the client-side JS can parse the pathname and do whatever it wants with it. 

> Why would that not work? There should be a page at 7/index.html is they want to serve HTML at /7

@victoriabernard92 This is a slightly different problem than that – if I want to render a React component for the route `/7`, I need to still load my client app from `/index.html`, while keeping the route up to date. The [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API) would update the URL accordingly as I navigate through apps, but the Worker shoudl always just return `/index.html`.

**Comment by victoriabernard92** [comment]
I see.  I was confused because ReavelJS is working for me. Its also SPA as When I request for `/#/3` for example still grabs `/` because the `#` is excluded from the path
![image](https://user-images.githubusercontent.com/7578652/66588111-615eec80-eb51-11e9-9183-7f7aa41ea74b.png)

>  just always look up index.html

IDK if that is the best approach because then we are making assumptions about behavior. I have actually been meaning for our docs to stop redirecting 404s to the overview page because it's not correct practice. If some manually types in `developers.cloudflare/workers/bogus` then we should tell them the page doesn't exist

I do see a point in doing something though. I suggest rather than just documenting it we prevent the behavior. Some ideas:
* send a warning to obvious SPA projects (e.g. your project only has one index.html.. do this..)  
* and/or provide a SPA template that is searchable by popular frameworks.

**Comment by signalnerve** [comment]
> I suggest rather than just documenting it we prevent the behavior

Yep! I don't think it should be the default. This is specifically for SPAs, we definitely want to keep functionality the same. 

> I was confused because ReavelJS is working for me. Its also SPA as When I request for /#/3 for example still grabs / because the # is excluded from the path

indeed! That's an alternate way of doing this – react-router calls this a [HashRouter](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/HashRouter.md), where everything after the `#` in the URL is used for client-side routing. It definitely works, but AFAICT most frameworks have moved towards using the History API and just modifying the URL directly.

I think it's pretty easy to imagine _how_ we'll write up this explanation, but I'm not sure on _where_ it should live. Would we publish a separate sites template that's 90% similar to our default, with a custom key handler? Do we write a guide for "Best Practices building SPAs with Workers Sites"? Open to ideas here, I'm not sure I feel like there's a clear obvious answer.

**Comment by signalnerve** [comment]
> I do see a point in doing something though. I suggest rather than just documenting it we prevent the behavior. Some ideas:
> - send a warning to obvious SPA projects (e.g. your project only has one index.html.. do this..)
>  - and/or provide a SPA template that is searchable by popular frameworks.

Re: this, I think my question about where this documentation should go will also answer this. It's a lot of work to start doing project detection on `init`, but I do think it's useful to give people some sort of starter guide when they set up a new project, because I imagine this is just one of many questions that will come up. Maybe we can output a URL to the docs when a user runs `init --site`, and then add this info there?

**Comment by victoriabernard92** [comment]
>  It's a lot of work to start doing project detection on init

Like it'd be hard for rust to read in those files? or why is this the case? 
>  output a URL to the docs when a user runs init --site
> Do we write a guide for "Best Practices building SPAs with Workers Sites"?

My concern is users won't know when to/ just won't read or follow it

> Would we publish a separate sites template..

Yes I think we should and have it live in the gallery and then as a note in the sites quickstart ("if using a SPA then run `wrangler generate https://...`  instead of `wrangler generate --site`

**Comment by signalnerve** [comment]
This came up [in the forums](https://community.cloudflare.com/t/cloudflare-workers-spa-with-vuejs/122864), and the following code seems to do the trick (tested with my own site):

```js
options.mapRequestToAsset = request => {
  const url = new URL(request.url)
  url.pathname = `/`
  return mapRequestToAsset(new Request(url, request))
}
```

**Comment by ashleymichal** [comment]
@signalnerve this map will return index.html for everything, including image assets etc.

**Comment by signalnerve** [comment]
> @signalnerve it looks like this map will return index.html for everything, including image assets etc.

indeed, this probably isn't a great fix. I updated my forum post to let him know it's probably not a perfect solution, and that we're going to think on it over the next week

**Comment by victoriabernard92** [comment]
fixed by using https://github.com/cloudflare/kv-asset-handler#servesinglepageapp

**Comment by spsaucier-bakkt** [comment]
@victoriabernard92 Using `serveSinglePageApp`, it's showing `"/" not found` for all routes for me. I've had to revert to using HashRouter/
