### ISSUE TITLE
Document caches.open()

### ISSUE THREAD

**Issue by rita3ko** [cloudflare/workers-docs#464]
Currently, we only document `caches.default` which uses the Cloudflare default cache, but we can also allow customers to open a namespaced cache that's not tied to the same cache as `fetch`.

**Comment by adaptive** [comment]
I remember that on Cache API Beta `caches.open("namespace")` was valid.
@rita3ko, is this still available?

**Comment by harrishancock** [comment]
@adaptive, yes, `caches.open()` has always been valid. We chose not to document it when we announced general availability of the Cache API because we bet that `caches.default` (which controls the same cache that `fetch()` can see) would cover all use cases. However, `caches.default` turns out to be more difficult to use correctly than we'd hoped, precisely because of the overlap with `fetch()`, so we think `caches.open()` is worth officially supporting.
