### ISSUE TITLE
Document return types

### ISSUE THREAD

**Issue by intellix** [cloudflare/workers-docs#567]
Just looking at this page: https://developers.cloudflare.com/workers/reference/storage/reading-data/

It states: 
> The full signature of the get method is:
> Namespace.get(key, [type])

But I don't see documentation anywhere about the return type. As a daily user of TypeScript it'd be nice to see the actual type definitions for the whole API.

Right now I'm having to rely on console.logs to see what stuff returns and have something like:

```ts
interface KvCacheEntry {
  list_complete: boolean;
  keys: Array<{
    expiration: number;
    name: string;
  }>;
}

interface KvCacheStorage {
  get(key: string, type?: 'text' | 'json' | 'arraybuffer' | 'stream'): Promise<string>;
  put(key: string, value: string, options: any): Promise<void>;
  list(options: any): Promise<KvCacheEntry>;
  delete(key: string): Promise<void>;
}
```

**Comment by signalnerve** [comment]
hey @intellix, this is a super good question. we've actually been talking about this in a few issues - #513, #565 - i don't want to speak for everyone on the team, so i'll say i'm generally +1 on writing the API docs in typescript format, but obviously it's a pretty huge undertaking and we want to figure out a game plan on how to proceed with it.

i'll tag in the rest of the team here and get their thoughts on it. i'd be interested to hear what they think about:

1) should we document our return types using typescript format?
2) if so, how should we tackle doing it?

IMO, answering 2, i think we can probably spin up a milestone/collection of issues for all the sections that need to be documented, i imagine folks would be interested in contributing to that kind of stuff 👍 

btw, just for the record: we do have https://github.com/cloudflare/workers-types available, feels like that would be a good resource to help us get up and running. 

btw 2, i'm summarizing all this up because i think it'd be cool to ship all this and make some noise in a GTM plan, and refer back to this issue 😄 cc @ashleygwilliams

**Comment by signalnerve** [comment]
oops, and i forgot the tag 😅 cc @cloudflare/workers-devexp
