### ISSUE TITLE
Debugging page doesn't render snippet

### ISSUE THREAD

**Issue by signalnerve** [cloudflare/workers-docs#569]
via Alex Mayorga in our internal chat, the debugging page is missing a snippet at the end of the page and seems to be cut off. 

cc @victoriabernard92, looks like the snippet was removed here? https://github.com/cloudflare/workers-docs/commit/9c706cf6b3b9c4246cb24567ec79792b1f2f4b73#diff-3cdad234222960f3c52a27004828db36L111

**Comment by victoriabernard92** [comment]
I wouldn't call this a bug I removed it on purpose because it didn't make sense with template pages

Some options:
- turn the debug page into just a template page
-  keep the snippet card at the end it just looked funny and will look even funnier with the new design 
- Just add a code block to the end of the debug page.

What do you think @signalnerve  ? Was the goal here just that they wanted to copy-paste the debug snippet code from that page and not go to the gallery?
