### ISSUE TITLE
RFC: Integrate spell-checker in CI / build process?

### ISSUE THREAD

**Issue by ispivey** [cloudflare/workers-docs#809]
To help contributors and take some burden off reviewers, it would be great if we could integrate automated spell-checking into our pipeline. 

https://www.npmjs.com/package/markdown-spellcheck is one such tool; I’m sure there are others. 

Questions:
1. Is this a good idea?
1. What do other documentation repos do?
1. What tool should we use?
1. Where should we integrate this in our pipeline, if we choose to do so?

**Comment by victoriabernard92** [comment]
I love this! While we are at it, prettier has also been driving me nuts. Can we include setting up husky into prettier with this RC? 
1. YES!
1. gatsby uses a github app [Typo CI](https://github.com/marketplace/typo-ci) and it looks free
1.  Looks like two options: an npm package [markdown-spellcheck](https://www.npmjs.com/package/markdown-spellcheck) or a Github app. I am not sure which I like better, but the npm package probably gives us more control since we can just run `npm run spellcheck`  in CI or with husky. Also it has 19k weekly downloads. What do you think? 
2. Husky and/or github actions I think makes sense
